version: 0.0
os: linux
files:
  - source: my_webserver/
    destination: /home/ec2-user/my_webserver
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: ec2-user
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 30
      runas: ec2-user
