version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t my_webserver/
  build:
    commands:
      - echo "Build phase complete"
artifacts:
  files:
    - appspec.yml
    - my_webserver/**/*
    - scripts/**/*
